version: '3.3'

services:
  aspnetapp:
    build: ../010-exercise-1-dockerfile
    ports:
    - "8081:80"     # The HTTP port
    environment: 
      - ASPNETCORE_URLS=http://+:80
  zap:
    image: owasp/zap2docker-weekly 
    command: zap-baseline.py -t http://aspnetapp
    depends_on:
      - aspnetapp