version: '3.3'

services:
  aspnetapp:
    build: ../010-exercise-1-dockerfile
    ports:
    - "8081:80"     # The HTTP port
    environment: 
      - ASPNETCORE_URLS=http://+:80
  sitespeed:
    image: sitespeedio/sitespeed.io
    command: --video false http://aspnetapp -n 3
    volumes:
      - .:/sitespeed.io
    depends_on:
      - aspnetapp